### ISSUE TITLE
AFNI Compile Failing on Ubuntu 20.04

### ISSUE THREAD

**Issue by N-Accumbens** [afni/afni#264]
Hi,

I'm trying to compile afni on my system and I was following the instructions on the frontpage.

Using the Makefile.linux_ubuntu_16_64 as a template, I copied it into Makefile and adjusted the installdir to /usr/local/afni/, a subfolder that I created.

Here is the error I got

```
/bin/rm -f pbar_color_defs.o
/usr/bin/gcc -O2 -m64 -fPIC -DREAD_WRITE_64 -DLINUX2 -Wcomment -Wformat -DUSE_TRACING -DHAVE_XDBE -D_GNU_SOURCE -DREPLACE_XT  -c pbar_color_defs.c -I. -I/usr/X11R6/include  -Icoxplot -Inifti/nifti2 -Inifti/niftilib -Inifti/nifticdf -Inifti/znzlib -I3DEdge/src -Irickr -Ileej3 -DHAVE_ZLIB -DHAVE_GIFTI  -If2c
In file included from afni.h:11,
                 from pbar_color_defs.c:1:
imseq.h:20:10: fatal error: Xm/Xm.h: No such file or directory
   20 | #include <Xm/Xm.h>
      |          ^~~~~~~~~
compilation terminated.
make: *** [Makefile.INCLUDE:1737: pbar_color_defs.o] Error 1
```

I've followed the instructions from 

https://afni.nimh.nih.gov/pub/dist/doc/htmldoc/background_install/install_instructs/steps_linux_ubuntu20.html 

up-to the install AFNI Binaries part.

Should I be using the Cmake system instead?

**Comment by leej3** [comment]
I'm biased so I can't advise :) I'm happy to help debug if you do have problems with the cmake build though.

Here's the docs for it:
https://afni.nimh.nih.gov/pub/dist/doc/htmldoc/devdocs/cmake_build/build_docs.html

**Comment by ccraddock** [comment]
Have you tried this:

https://askubuntu.com/questions/219414/installing-missing-package-that-provides-xm-xm-h

**Comment by mrneont** [comment]
Hi, @N-Accumbens -

Cmake would be one way to go, sure.  I note that I compile on Ubuntu 20.04 on my desktop, using make with the other_builds/Makefile.linux_ubuntu_16_64_glw_local_shared makefile (just copying that to "Makefile" in the main directory).

I have notes that I had to install the following as part of my build-processing:
```
sudo apt-get install libxpm-dev
sudo apt-get install libgsl-dev
sudo apt-get install libxi-dev
sudo apt-get install libglib2.0-dev   # for GLIB - version >= 2.4.0.
```

Some of these dependencies are listed in the other_builds/OS_notes.linux_ubuntu_16_64 text file, that has notes about dependencies for building on that older version of Ubuntu 16.04:
```
sudo apt-get update ; sudo apt-get upgrade

sudo apt-get install -y tcsh vim
sudo apt-get install -y libxmu-dev libxt-dev libmotif-dev
sudo apt-get install -y libxpm-dev libxi-dev libxmhtml-dev
sudo apt-get install -y libglw1-mesa-dev libglu1-mesa-dev
sudo apt-get install -y libglib2.0-dev libgsl-dev
sudo apt-get install -y r-base m4
sudo apt-get install -y python-qt4                         # modern note: not required/used at present
```

--pt

**Comment by N-Accumbens** [comment]
> Have you tried this:
> 
> https://askubuntu.com/questions/219414/installing-missing-package-that-provides-xm-xm-h

This did it for me, though I should note that I also installed the below packages + used the below makefile

> Hi, @N-Accumbens -
> 
> Cmake would be one way to go, sure. I note that I compile on Ubuntu 20.04 on my desktop, using make with the other_builds/Makefile.linux_ubuntu_16_64_glw_local_shared makefile (just copying that to "Makefile" in the main directory).
> 
> I have notes that I had to install the following as part of my build-processing:
> 
> ```
> sudo apt-get install libxpm-dev
> sudo apt-get install libgsl-dev
> sudo apt-get install libxi-dev
> sudo apt-get install libglib2.0-dev   # for GLIB - version >= 2.4.0.
> ```
> 
> Some of these dependencies are listed in the other_builds/OS_notes.linux_ubuntu_16_64 text file, that has notes about dependencies for building on that older version of Ubuntu 16.04:
> 
> ```
> sudo apt-get update ; sudo apt-get upgrade
> 
> sudo apt-get install -y tcsh vim
> sudo apt-get install -y libxmu-dev libxt-dev libmotif-dev
> sudo apt-get install -y libxpm-dev libxi-dev libxmhtml-dev
> sudo apt-get install -y libglw1-mesa-dev libglu1-mesa-dev
> sudo apt-get install -y libglib2.0-dev libgsl-dev
> sudo apt-get install -y r-base m4
> sudo apt-get install -y python-qt4                         # modern note: not required/used at present
> ```
> 
> Note that at the bottom of this text file are some fancy footwork steps to deal with GLwDrawA.h funniness---those should _not_ be needed with the Makefile*_glw_local_shared makefile, so I won't list them here.
> 
> I would try installing the first dependencies, and see if that sorts everything build-wise. Some of the second batch might be necessary, too.
> 
> --pt
